n_warmup_steps = 50000
# n_warmup_steps = 100
n_total_steps = 50000000
n_total_episodes = 600
n_stack_frames = 4

result_dir = "results/async_dqn/{env_id}/{now}"


[replay]
# limit = 1000000  # requires approximately 62.5 GB memory (with `n_action_repeat = 4`)
# limit = 800000  # requires approximately 50 GB memory (with `n_action_repeat = 4`)
limit = 400000  # requires approximately 25 GB memory (with `n_action_repeat = 4`)

[policy]

[policy.params]
initial_epsilon = 1.0
final_epsilon = 0.1
# final_exploration_step = 1000000
final_exploration_step = 4000000


[optimizer]
optimizer = "RMSprop"

[optimizer.params]
lr = 0.00025
alpha = 0.95
eps = 0.01


[learner]
gamma = 0.99
batch_size = 32
target_network_update_freq = 10000
# target_network_update_soft = 0.01

[actor]
n_action_repeat = 4
n_random_actions_at_reset = [0, 30]  # will be converted to tuple

[history]
# 1 episodes dump requres approximately 30 MB disk (in AlienNoFrameskip-v4. Twice the value if you have a greedy actor).
# disk usage: n_total_steps / mean(episode_steps) / render_episode_freq * 2 * mean(gif_file) (MB).
# NOTE: CUDA (and its dependencies) requires approximately 6 GB.
# render_episode_freq = 0: means no rendering
# render_episode_freq = 25  # requres 50 GB (in AlienNoFrameskip-v4)
# render_episode_freq = 50  # requres 30 GB (in AlienNoFrameskip-v4)
render_episode_freq = 100  # requres 18 GB (in AlienNoFrameskip-v4)
# render_episode_freq = 3
