# n_warmup_steps = 50000
n_warmup_steps = 1000

n_total_steps = 50000000


[replay]
limit = 1000000


[policy]

[policy.params]
initial_epsilon = 1.0
final_epsilon = 0.1
final_exploration_step = 1000000


[optimizer]
optimizer = "RMSprop"

[optimizer.params]
lr = 0.00025
alpha = 0.95
eps = 0.01


[learner]
gamma = 0.99
batch_size = 32
